HOST = "localhost"
PORT = 2000
TIMEOUT = 20.0

CAR_NAME = 'mkz_2017'
EPISODE_LENGTH = 600
NUMBER_OF_VEHICLES = 30
NUMBER_OF_PEDESTRIAN = 100
CONTINUOUS_ACTION = True
VISUAL_DISPLAY = True

OBS_SHAPE = 2048+6


RGB_CAMERA = 'sensor.camera.rgb'
SSC_CAMERA = 'sensor.camera.semantic_segmentation'

